<template>
  <div class="about">
    <AboutContent heading="OUR MISSION"
                  content='OUR MISSION IS TO CREATE HONEST, INVENTIVE AND THOUGHTFUL DISHES THAT ARE MORE THAN JUST "BAR FOOD". FROM CAREFULLY CRAFTED GYROS AND SANDWICHES, TO WINGS, SALADS AND EVEN OUR MADE-FROM-SCRATCH SOUP, WE HAVE FOOD FOR EVERYONE INCLUDING DELICIOUS GLUTEN FREE OPTIONS. OUR TEAM IS HERE TO PROVIDE IMPECCABLE SERVICE, AND HIGH QUALITY FOOD AND BEVERAGES, WHILE GIVING YOU A LOCAL PLACE WHERE YOU CAN COME EXCHANGE SOME STORIES AND LAUGHS.'/>
    <AboutContent heading="THE OWNERS"
                  content="THE 408 OWNERS ARE A GROUP OF FRIENDS WHO HAVE KNOWN EACH OTHER FOR YEARS AND YEARS. JONATHAN, LAMAR AND BOB TRUST AND RELY ON EACH OTHER FOR ALL SORTS OF BUSINESS VENTURES, AND HAD A VISION OF OWNING A SMALL LOCAL TAVERN WHERE ALL THE LOCALS FEEL AT HOME. THE MANAGING OWNER, JONATHAN, GREW UP WORKING IN RESTAURANTS, AND DEVELOPING HIS SKILLS IN A VARIETY OF KITCHENS. HE AND HIS WIFE HAVE OWNED TWO DIFFERENT RESTUARANT FRANCHISES, AND HAVE BEEN DREAMING OF THE DAY THEY COULD CREATE THEIR OWN PLACE WITH THEIR OWN DISHES. WITH FOUR CHILDREN OF THEIR OWN, JONATHAN AND HIS FAMILY ARE BUSY, BUT HAVE TAKEN THE TIME TO POUR THEIR HEART AND SOUL INTO THE 408 EXCHANGE."/>
    <AboutContent heading="ABOUT THE NAME"
                  content="WHY DID WE CHOOSE THE NAME 408? BECAUSE IT'S THE STREET NUMBER OF OUR BUILDING! WHY DID WE CHOOSE THE EXCHANGE AS PART OF OUR NAME? IT'S A NOD TO THE RAILROAD THAT HAS RUN BEHIND OUR BUILDING FOR DECADES, AND IT'S IN REFERENCE TO ALL THAT IS EXCHANGED IN A LOCAL BUSINESS. WE CHOSE THIS SMALL SPACE BECAUSE OF ITS LOCATION, ITS HISTORY AND BECAUSE WE WANT THAT SMALL LOCAL TAVERN WHERE 'EVERYBODY KNOWS YOUR NAME'. COME FOR THE GOOD FOOD AND DRINKS, STAY FOR THE CONVERSATION AND SERVICE."/>
    <AboutContent heading="THE HISTORY OF 408"
                  content="THOUGH OUR BUSINESS IS NEW, OUR BUILDING IS VERY OLD. FOUNDED IN 1889 AS A BUTCHER SHOP, THIS BUILDING HAS HOSTED NUMBEROUS BUSINESSES SINCE THAT TIME. WE LOVE THE HISTORY OF EACH BUSINESS, AND HAVE TRIED TO ADD LITTLE TREASURES AROUND OUR SPACE TO HONOR THOSE PAST BUSINESSES. WE WON'T SPOIL THE FUN BY TELLING YOU ABOUT ALL THE DIFFERNT BUSINESSES AND TREASURES WE'VE ADDED,INSTEAD COME IN, GRAB A SEAT AND FIND OUT FOR YOURSELF. THIS IS A PLACE TO EXCHANGE STORIES, AND THIS BUILDING HAS MANY TO TELL."/>
    <img class="darkLogo" src="@/assets/408LogoDarkBG.svg" alt="main logo" width="200" height="100">
  </div>
</template>

<script>
import AboutContent from '@/components/aboutComponents/AboutContent.vue'

export default {
  name: 'About',
  components: {
    AboutContent,
  }
}
</script>

<style scoped>
.about {
  /* background-color: #07070f; */
  color: #ced0cf;
  padding-top: 10px;
  align-self: center;

  display: grid;
  /* grid-template-columns: 1fr; */
  place-items: center;
  width: 100vw;
  max-width: 900px;
}

.darkLogo {
  width: 90%;
  height: auto;
  max-width: 640px;
  margin: -20px;
}
</style>
